output:
  print-linter-name: true
linters:
    enable:
      - errcheck
      - gosimple
      - govet
      - ineffassign
      - staticcheck
      - unused
      - bodyclose
      - govet
      - gosec
      - errcheck